import React from 'react'
import { FaDatabase, FaTransgenderAlt } from 'react-icons/fa'

const MenuItemIcons = {
    '/locationList': <img src="/dist/SVGs/Locations.svg" className="sidebarIcons" />,
    '/holidayCalendarList': <img src="/dist/SVGs/Holidaycalenders.svg" className="sidebarIcons" />,
    '/leaveTypeList': <img src="/dist/SVGs/Leavetypes.svg" className="sidebarIcons" />,
    '/emailTemplateList': <img src="/dist/SVGs/Emailtemplates.svg" className="sidebarIcons" />,
    '/employeeList': <img src="/dist/SVGs/Employees.svg" className="sidebarIcons" />,
    '/clientList': <img src="/dist/SVGs/Clients.svg" className="sidebarIcons" />,
    '/projectList': <img src="/dist/SVGs/Projects.svg" className="sidebarIcons" />,
    '/userList': <img src="/dist/SVGs/Users.svg" className="sidebarIcons" />,
    '/roleList': <img src="/dist/SVGs/Roles.svg" className="sidebarIcons" />,
    '/leaveList': <img src="/dist/SVGs/Apply.svg" className="sidebarIcons" />,
    '/authorizeLeaves': <img src="/dist/SVGs/Authorize.svg" className="sidebarIcons" />,
    '/timesheetList': <img src="/dist/SVGs/Apply.svg" className="sidebarIcons" />,
    '/authorizeTimesheet': <img src="/dist/SVGs/Authorize.svg" className="sidebarIcons" />,
    '/subscriberList': <img src="/dist/SVGs/Subscribers.svg" className="sidebarIcons" />,
    '/emailDefaultList': (
        <img src="/dist/OceanImages/emailTemplatesappown.png" className="sidebarIcons" />
    ),
    '/organizationProfiles': <img src="/dist/SVGs/Orgprofile.svg" className="sidebarIcons" />,
    '/leaveBalances': <img src="/dist/SVGs/Leavebalance.svg" className="sidebarIcons" />,
    '/expenses': <img src="/dist/SVGs/Expensescategories.svg" className="sidebarIcons" />,
    '/expensesList': <img src="/dist/SVGs/Apply.svg" className="sidebarIcons" />,
    '/authorizeExpenseList': <img src="/dist/SVGs/Authorize.svg" className="sidebarIcons" />,
    '/reimburseList': <img src="/dist/SVGs/Reimburse.svg" className="sidebarIcons" />,
    '/endpoints': <img src="/dist/SVGs/Endpoints.svg" className="sidebarIcons" />,
    '/screenList': <img src="/dist/SVGs/Screens.svg" className="sidebarIcons" />,
    '/moduleList': <img src="/dist/SVGs/Modules.svg" className="sidebarIcons" />,
    '/appraisalList': <img src="/dist/SVGs/Apply.svg" className="sidebarIcons" />,
    '/authorizeAppraisalList': <img src="/dist/SVGs/Authorize.svg" className="sidebarIcons" />,
    '/performanceAppraisal': <img src="/dist/SVGs/Generate.svg" className="sidebarIcons" />,
    '/HRReviewList': <img src="/dist/SVGs/Review.svg" className="sidebarIcons" />,
    '/countryList': <img src="/dist/SVGs/Countries.svg" className="sidebarIcons" />,
    '/currencyList': <img src="/dist/SVGs/Currencies.svg" className="sidebarIcons" />,
    '/employmentTypeList': <img src="/dist/SVGs/Employeetypes.svg" className="sidebarIcons" />,
    '/familyRelationTypeList': <img src="/dist/SVGs/Family.svg" className="sidebarIcons" />,
    '/idProofTypeList': <img src="/dist/SVGs/Idproofs.svg" className="sidebarIcons" />,
    '/skillLevelList': <img src="/dist/SVGs/Skilllevels.svg" className="sidebarIcons" />,
    '/emailEventList': <img src="/dist/SVGs/Emailevents.svg" className="sidebarIcons" />,
    '/announcementList': <img src="/dist/SVGs/Announcements.svg" className="sidebarIcons" />,
    '/peerReviewList': <img src="/dist/SVGs/Review.svg" className="sidebarIcons" />,
    '/departmentList': <img src="/dist/SVGs/Departments.svg" className="sidebarIcons" />,
    '/expensesReports': <img src="/dist/SVGs/Expenses.svg" className="sidebarIcons" />,
    '/leavesReports': <img src="/dist/SVGs/Leaves.svg" className="sidebarIcons" />,
    '/timesheetsweeklyReports': <img src="/dist/SVGs/Timesheets.svg" className="sidebarIcons" />,
    '/timesheetsMonthlyReports': <img src="/dist/SVGs/Timesheets.svg" className="sidebarIcons" />,
    '/appraisalReports': <img src="/dist/SVGs/Performanceappraisal.svg" className="sidebarIcons" />,
    '/employeeReports': <img src="/dist/SVGs/Employees.svg" className="sidebarIcons" />,
    '/headList': <img src="/dist/SVGs/Salaryheads.svg" className="sidebarIcons" />,
    '/salaryComponentList': <img src="/dist/SVGs/Salarycomponents.svg" className="sidebarIcons" />,
    '/salaryTemplateList': <img src="/dist/SVGs/Salarytemplates.svg" className="sidebarIcons" />,
    '/compensationHistory': <img src="/dist/SVGs/Compensation.svg" className="sidebarIcons" />,
    '/loanTracking': <img src="/dist/SVGs/Salaryadvance.svg" className="sidebarIcons" />,
    '/payrunList': <img src="/dist/SVGs/Payrun.svg" className="sidebarIcons" />,
    '/payslip': <img src="/dist/SVGs/payslip.svg" className="sidebarIcons" />,
    '/myPayslips': <img src="/dist/SVGs/payslip.svg" className="sidebarIcons" />,
    Subscribers: <img src="/dist/SVGs/Subscribers.svg" className="sidebarIcons" />,
    'Master Data': <FaDatabase className="text-white" size={20} />,
    'Default Data': <img src="/dist/OceanImages/defaultdata.png" className="sidebarIcons" />,
    Security: <img src="/dist/SVGs/Security.svg" className="sidebarIcons" />,
    Organization: <img src="/dist/SVGs/Org.svg" className="sidebarIcons" />,
    Users: <img src="/dist/SVGs/Users.svg" className="sidebarIcons" />,
    Leaves: <img src="/dist/SVGs/Leaves.svg" className="sidebarIcons" />,
    Timesheets: <img src="/dist/SVGs/Timesheets.svg" className="sidebarIcons" />,
    Expenses: <img src="/dist/SVGs/Expenses.svg" className="sidebarIcons" />,
    Employees: <img src="/dist/SVGs/Employees.svg" className="sidebarIcons" />,
    // 'Performence Appraisals':<img  src='/dist/OceanImages/appraisal.png' className='sidebarIcons'/>,
    'Performance Appraisal': (
        <img src="/dist/SVGs/Performanceappraisal.svg" className="sidebarIcons" />
    ),
    Feedback: <img src="/dist/OceanImages/feedback.png" className="sidebarIcons" />,
    Reports: <img src="/dist/SVGs/Reports.svg" className="sidebarIcons" />,
    Payroll: <img src="/dist/SVGs/Payroll.svg" className="sidebarIcons" />,
    '/taxRulesList': <img src="/dist/SVGs/Taxrules.svg" className="sidebarIcons" />,
    '/genderList': <FaTransgenderAlt className="text-white" size={20} />,
    '/maritalStatusList': <img src="/dist/SVGs/Maritalstatus.svg" className="sidebarIcons" />,
    'Support Tickets': <img src="/dist/SVGs/Supporttickets.svg" className="sidebarIcons" />,
    '/feedbackList': <img src="/dist/SVGs/Supporttickets.svg" className="sidebarIcons" />,
    Help: <img src="/dist/SVGs/Supporttickets.svg" className="sidebarIcons" />,
    '/jobRoleList': <img src="/dist/SVGs/Roles.svg" className="sidebarIcons" />,
    '/projectStatusList': <img src="/dist/SVGs/Projects.svg" className="sidebarIcons" />,
    Dashboard: <img src="/dist/Images/dashboardIcon.png" className="sidebarIcons" />,
    Resignations: <img src="/dist/Images/resignation.png" className="sidebarIcons" />,
    '/resignationList': <img src="/dist/Images/resignation.png" className="sidebarIcons" />,
    '/fullAndFinalSettllementList': (
        <img src="/dist/Images/sponsorship 1.png" className="sidebarIcons" />
    ),
    '/resignationManagerList': <img src="/dist/SVGs/Review.svg" className="sidebarIcons" />,
    '/resignationHRList': <img src="/dist/SVGs/Authorize.svg" className="sidebarIcons" />,
    '/managerAttendanceReports': (
        <img src="/dist/Images/TodayAttendance.png" className="sidebarIcons" />
    )
}

export default MenuItemIcons
